name: Regression Tests
on: [push]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: sudo apt-get install -y bmake
    - name: Configure
      run: |
        cat /etc/os-release
        ./configure
    - name: Build and test
      run: bmake regress
  linux_libbsd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: sudo apt-get install -y bmake pkg-config libbsd-dev
    - name: Configure
      run: |
        cat /etc/os-release
        CFLAGS=$(pkg-config --cflags libbsd-overlay) ./configure CPPFLAGS="-DENABLE_SECCOMP_FILTER=1" LDFLAGS=$(pkg-config --libs libbsd-overlay)
    - name: Build and test
      run: bmake regress
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: brew install bmake
    - name: Configure
      run: ./configure
    - name: Build and test
      run: bmake regress
  freebsd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Test in FreeBSD
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        prepare: pkg install -y curl
        run: |
          freebsd-version
          ./configure
          make regress
  netbsd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Test in NetBSD
      uses: vmactions/netbsd-vm@v1
      with:
        usesh: true
        prepare: /usr/sbin/pkg_add curl
        run: |
          uname -a
          ./configure
          make regress
  solaris:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Test in Solaris
      uses: vmactions/solaris-vm@v0
      with:
        usesh: true
        prepare: pkgutil -y -i socat
        run: |
          cat /etc/release
          ./configure
          make regress
  dragonflybsd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Test in DragonflyBSD
      uses: vmactions/dragonflybsd-vm@v0
      with:
        usesh: true
        prepare: pkg install -y curl
        run: |
          uname -a
          ./configure
          make regress
